### ISSUE TITLE
No support for delay, space or dividers in sequence charts

### ISSUE THREAD

**Issue by 27escape** [sonyxperiadev/dataflow#4]
Being able to separate parts of a sequence is extremely valuable, plantuml has ... ==divider == and |||.

Is there any intention to support this sort of functionality in the future, lifelines would also be useful but I can live without those if there is some sort of spacer.

Thanks for the work on dataflow so far, I am liking the syntax and find its easier to do what I want than finding plantuml suddenly swaps from a sequence chart to a UML/graphviz style one!

cheers
kevin

**Comment by owickstrom** [comment]
Thanks for your suggestion and kind words! :)

I'll look into it, but at a quick glance it looks like something specific to sequence diagrams, which actually is just a "bonus output" for the DataFlow tool, which primarily focuses on DFDs. However, my colleague knows a lot more about DFDs and something like this might be useful there as well, so I'll ask.

/Oskar

**Comment by owickstrom** [comment]
Sorry, but this will not be included in DataFlow. I think the feature you're requesting belongs in a sequence diagram and that it's outside the DFD scope.

I guess you could do some hack with trust boundaries but that's probably not what you are looking for. Perhaps the best thing would be to create two separate diagrams and then group them in the document or wherever you are displaying them?

Thanks again!
