### ISSUE TITLE
cabal install dataflow not working

### ISSUE THREAD

**Issue by dakra** [sonyxperiadev/dataflow#7]
Hi, I'm having trouble installing dataflow.
I never used cabal before so maybe I do some basic task wrong.
Below is the cabal version and the install command output.
Thanks.
```
λ cabal --version
cabal-install version 2.4.0.0
compiled using version 2.4.0.1 of the Cabal library 

λ cabal v1-install dataflow
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: dataflow-0.7.3.0 (user goal)
[__1] trying: hastache-0.6.1 (dependency of dataflow)
[__2] next goal: base (dependency of dataflow)
[__2] rejecting: base-4.12.0.0/installed-4.1... (conflict: hastache =>
base>=4.4 && <4.11)
[__2] rejecting: base-4.12.0.0, base-4.11.1.0, base-4.11.0.0, base-4.10.1.0,
base-4.10.0.0, base-4.9.1.0, base-4.9.0.0, base-4.8.2.0, base-4.8.1.0,
base-4.8.0.0, base-4.7.0.2, base-4.7.0.1, base-4.7.0.0, base-4.6.0.1,
base-4.6.0.0, base-4.5.1.0, base-4.5.0.0, base-4.4.1.0, base-4.4.0.0,
base-4.3.1.0, base-4.3.0.0, base-4.2.0.2, base-4.2.0.1, base-4.2.0.0,
base-4.1.0.0, base-4.0.0.0, base-3.0.3.2, base-3.0.3.1 (constraint from
non-upgradeable package requires installed instance)
[__2] fail (backjumping, conflict set: base, dataflow, hastache)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base, dataflow, hastache
Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.
```

**Comment by owickstrom** [comment]
Hi! This is a problem in `dataflow` with version bounds, let me fix that.

Also, I can recommend installing using `cabal v2-install` instead to avoid clashing dependencies with other Cabal-installed packages.

**Comment by owickstrom** [comment]
Turns out this wasn't as easy as loosening version bounds. The `hastache` library that `dataflow` depends on doesn't compile with newer GHC compilers, it seems: https://github.com/lymar/hastache/issues/55

**Comment by owickstrom** [comment]
The best way to fix this would be to port over to the new `mustache` library, but I don't have much time to do that now.

A workaround for you would be to obtain a GHC 7.x and install with that, either through your OS package manager or using [Stack](https://docs.haskellstack.org/en/stable/README/). I'm not sure this command would work (don't have Stack myself) but something like:

```
stack --resolver lts-6.35 install dataflow
```

**Comment by dakra** [comment]
OK. Thanks for looking into it.

I'll leave the issue open as it is not resolved yet but feel free to close if you want :)

**Comment by owickstrom** [comment]
Sure @dakra. I'm closing this and creating a new one for migrating over to `mustache`. Thank you for reporting!

**Comment by andrsnn** [comment]
FYI `stack --resolver lts-6.35 install dataflow` to compile correctly on Linux Mint 19.1 :+1:

**Comment by owickstrom** [comment]
Thanks @andrsnn!
